theme: jekyll-theme-minimal
title: J677's homepage
description: A portfolio of some of my works. <img width="1920" height="1920" alt="J677Portfolio" src="https://github.com/user-attachments/assets/6a327596-707c-47fe-9daf-80f97d28b920" />
